version: '3'
services:
  ad_drone:
    image: ad_drone_image

    build: .

    volumes:
      - ./data/drones.csv:/app/data/drones.csv
      - ./cert_engine.pem:/app/cert_engine.pem
      - ./cert_registry.pem:/app/cert_registry.pem

    tty: true


# docker-compose -f docker-runRegistry.yaml run ad_drone_run_registry python app/src/runnerEngine.py
# sudo docker inspect ad_registry_container | grep IPAddress
