version: '3'

services:
  ad_engine:
    container_name: ad_engine_container

    build: .
    
    ports:
      - "8080:8080"

    volumes:
      - ./AD_Database/database.db:/app/AD_Database/database.db


    working_dir: /app
    
    tty: true
    command: ["npm", "run", "build:start"]
